### ISSUE TITLE
configuring fails with autoconf 2.63 on rhel6.8

### ISSUE THREAD

**Issue by berndloerwald** [IOR-LANL/ior#15]
`autoconf (GNU Autoconf) 2.63` fails to configure if `AC_CONFIG_*` comes before `AC_INIT` (as it does since https://github.com/IOR-LANL/ior/commit/77590f4e505ef25fb13f5f99b82f336a8d001095#diff-67e997bcfdac55191033d57a16d1408aR5). That version is the default on rhel6.8.

It was also required to add `ACLOCAL_AMFLAGS = -I config` to `Makefile.am` in order to find `X_AC_META` and `AX_PROG_CC_MPI` correctly in the `aclocal` run. 

Proposed diff:

```diff
diff --git a/Makefile.am b/Makefile.am
index 685d716..377338f 100755
--- a/Makefile.am
+++ b/Makefile.am
@@ -1,2 +1,3 @@
 SUBDIRS = src doc contrib
 EXTRA_DIST = META COPYRIGHT README ChangeLog
+ACLOCAL_AMFLAGS = -I config
diff --git a/configure.ac b/configure.ac
index 3361572..4de4a66 100755
--- a/configure.ac
+++ b/configure.ac
@@ -2,9 +2,8 @@
 # Process this file with autoconf to produce a configure script.
 
 AC_PREREQ([2.62])
-AC_CONFIG_MACRO_DIR([config])
-
 AC_INIT([META_PACKAGE_NAME],[META_PACKAGE_VERSION],[],[META_PACKAGE_NAME])
+AC_CONFIG_MACRO_DIR([config])
 
 X_AC_META
 
```

**Comment by glennklockwood** [comment]
Thanks for reporting this.  I confirmed that `ACLOCAL_AMFLAGS = -I config` is required to bootstrap using autoconf as new as 2.67.  I also confirmed that your proposed change to `configure.ac` doesn't break on newer autoconfs, but was unable to verify the issue (or fix) since I don't have older autoconf handy.

Your proposed patches are in as of b0bffa0, so could you take a look and confirm that they fix the issues you encountered on EL6.8?

**Comment by berndloerwald** [comment]
Can confirm that 6faf076f118c856c3b7f0783c348bff4eb84abd0 bootstraps, configures and makes fine on the host previously having the issue.
